// Code generated by protoc-gen-go. DO NOT EDIT.
// source: globalrouting.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocalityTrafficPolicy_LbType int32

const (
	//Traffic with be routed to local locality first
	//if there are no health instances in the local locality traffic will be routed to
	//remote locality
	LocalityTrafficPolicy_TOPOLOGY LocalityTrafficPolicy_LbType = 0
	LocalityTrafficPolicy_FAILOVER LocalityTrafficPolicy_LbType = 1
)

var LocalityTrafficPolicy_LbType_name = map[int32]string{
	0: "TOPOLOGY",
	1: "FAILOVER",
}

var LocalityTrafficPolicy_LbType_value = map[string]int32{
	"TOPOLOGY": 0,
	"FAILOVER": 1,
}

func (x LocalityTrafficPolicy_LbType) String() string {
	return proto.EnumName(LocalityTrafficPolicy_LbType_name, int32(x))
}

func (LocalityTrafficPolicy_LbType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5c0dc509add6f4f, []int{1, 0}
}

type GlobalTrafficPolicy struct {
	// OPTIONAL: A list host name .
	TrafficPolicy []*LocalityTrafficPolicy `protobuf:"bytes,1,rep,name=trafficPolicy,proto3" json:"trafficPolicy,omitempty"`
	//OPTIONAL: defines traffic percentages to be sent to different label-based segments
	SegmentPolicy []*SegmentRoutingPolicy `protobuf:"bytes,2,rep,name=segmentPolicy,proto3" json:"segmentPolicy,omitempty"`
	// REQUIRED: dns that can be used by client.  This name will have the
	// traffic type applied to it
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// REQUIRED: One or more labels that indicate a specific set of pods/VMs
	// on which this global routing policy should be applied. The scope of
	// label search is restricted to namespace mark for mesh enablement
	// this will scan all cluster and namespace
	Selector             map[string]string `protobuf:"bytes,4,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GlobalTrafficPolicy) Reset()         { *m = GlobalTrafficPolicy{} }
func (m *GlobalTrafficPolicy) String() string { return proto.CompactTextString(m) }
func (*GlobalTrafficPolicy) ProtoMessage()    {}
func (*GlobalTrafficPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c0dc509add6f4f, []int{0}
}

func (m *GlobalTrafficPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalTrafficPolicy.Unmarshal(m, b)
}
func (m *GlobalTrafficPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalTrafficPolicy.Marshal(b, m, deterministic)
}
func (m *GlobalTrafficPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalTrafficPolicy.Merge(m, src)
}
func (m *GlobalTrafficPolicy) XXX_Size() int {
	return xxx_messageInfo_GlobalTrafficPolicy.Size(m)
}
func (m *GlobalTrafficPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalTrafficPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalTrafficPolicy proto.InternalMessageInfo

func (m *GlobalTrafficPolicy) GetTrafficPolicy() []*LocalityTrafficPolicy {
	if m != nil {
		return m.TrafficPolicy
	}
	return nil
}

func (m *GlobalTrafficPolicy) GetSegmentPolicy() []*SegmentRoutingPolicy {
	if m != nil {
		return m.SegmentPolicy
	}
	return nil
}

func (m *GlobalTrafficPolicy) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GlobalTrafficPolicy) GetSelector() map[string]string {
	if m != nil {
		return m.Selector
	}
	return nil
}

// TrafficPolicy describes routing for a hostname.
type LocalityTrafficPolicy struct {
	// REQUIRED: type of global load distrubtion
	LbType LocalityTrafficPolicy_LbType `protobuf:"varint,2,opt,name=lbType,proto3,enum=admiral.global.v1alpha.LocalityTrafficPolicy_LbType" json:"lbType,omitempty"`
	//weigth of primary and secondary must each 100
	Target               []*TrafficGroup `protobuf:"bytes,3,rep,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LocalityTrafficPolicy) Reset()         { *m = LocalityTrafficPolicy{} }
func (m *LocalityTrafficPolicy) String() string { return proto.CompactTextString(m) }
func (*LocalityTrafficPolicy) ProtoMessage()    {}
func (*LocalityTrafficPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c0dc509add6f4f, []int{1}
}

func (m *LocalityTrafficPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalityTrafficPolicy.Unmarshal(m, b)
}
func (m *LocalityTrafficPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalityTrafficPolicy.Marshal(b, m, deterministic)
}
func (m *LocalityTrafficPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalityTrafficPolicy.Merge(m, src)
}
func (m *LocalityTrafficPolicy) XXX_Size() int {
	return xxx_messageInfo_LocalityTrafficPolicy.Size(m)
}
func (m *LocalityTrafficPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalityTrafficPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_LocalityTrafficPolicy proto.InternalMessageInfo

func (m *LocalityTrafficPolicy) GetLbType() LocalityTrafficPolicy_LbType {
	if m != nil {
		return m.LbType
	}
	return LocalityTrafficPolicy_TOPOLOGY
}

func (m *LocalityTrafficPolicy) GetTarget() []*TrafficGroup {
	if m != nil {
		return m.Target
	}
	return nil
}

//describes label-based routing
type SegmentRoutingPolicy struct {
	Segments             []*SegmentGroup `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SegmentRoutingPolicy) Reset()         { *m = SegmentRoutingPolicy{} }
func (m *SegmentRoutingPolicy) String() string { return proto.CompactTextString(m) }
func (*SegmentRoutingPolicy) ProtoMessage()    {}
func (*SegmentRoutingPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c0dc509add6f4f, []int{2}
}

func (m *SegmentRoutingPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentRoutingPolicy.Unmarshal(m, b)
}
func (m *SegmentRoutingPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentRoutingPolicy.Marshal(b, m, deterministic)
}
func (m *SegmentRoutingPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentRoutingPolicy.Merge(m, src)
}
func (m *SegmentRoutingPolicy) XXX_Size() int {
	return xxx_messageInfo_SegmentRoutingPolicy.Size(m)
}
func (m *SegmentRoutingPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentRoutingPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentRoutingPolicy proto.InternalMessageInfo

func (m *SegmentRoutingPolicy) GetSegments() []*SegmentGroup {
	if m != nil {
		return m.Segments
	}
	return nil
}

type SegmentGroup struct {
	Segment              string   `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	Weight               float32  `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentGroup) Reset()         { *m = SegmentGroup{} }
func (m *SegmentGroup) String() string { return proto.CompactTextString(m) }
func (*SegmentGroup) ProtoMessage()    {}
func (*SegmentGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c0dc509add6f4f, []int{3}
}

func (m *SegmentGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentGroup.Unmarshal(m, b)
}
func (m *SegmentGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentGroup.Marshal(b, m, deterministic)
}
func (m *SegmentGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentGroup.Merge(m, src)
}
func (m *SegmentGroup) XXX_Size() int {
	return xxx_messageInfo_SegmentGroup.Size(m)
}
func (m *SegmentGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentGroup proto.InternalMessageInfo

func (m *SegmentGroup) GetSegment() string {
	if m != nil {
		return m.Segment
	}
	return ""
}

func (m *SegmentGroup) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type TrafficGroup struct {
	//region for the traffic
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	//weight for traffic this region should get.
	Weight               int32    `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrafficGroup) Reset()         { *m = TrafficGroup{} }
func (m *TrafficGroup) String() string { return proto.CompactTextString(m) }
func (*TrafficGroup) ProtoMessage()    {}
func (*TrafficGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5c0dc509add6f4f, []int{4}
}

func (m *TrafficGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrafficGroup.Unmarshal(m, b)
}
func (m *TrafficGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrafficGroup.Marshal(b, m, deterministic)
}
func (m *TrafficGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficGroup.Merge(m, src)
}
func (m *TrafficGroup) XXX_Size() int {
	return xxx_messageInfo_TrafficGroup.Size(m)
}
func (m *TrafficGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficGroup proto.InternalMessageInfo

func (m *TrafficGroup) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *TrafficGroup) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterEnum("admiral.global.v1alpha.LocalityTrafficPolicy_LbType", LocalityTrafficPolicy_LbType_name, LocalityTrafficPolicy_LbType_value)
	proto.RegisterType((*GlobalTrafficPolicy)(nil), "admiral.global.v1alpha.GlobalTrafficPolicy")
	proto.RegisterMapType((map[string]string)(nil), "admiral.global.v1alpha.GlobalTrafficPolicy.SelectorEntry")
	proto.RegisterType((*LocalityTrafficPolicy)(nil), "admiral.global.v1alpha.LocalityTrafficPolicy")
	proto.RegisterType((*SegmentRoutingPolicy)(nil), "admiral.global.v1alpha.SegmentRoutingPolicy")
	proto.RegisterType((*SegmentGroup)(nil), "admiral.global.v1alpha.SegmentGroup")
	proto.RegisterType((*TrafficGroup)(nil), "admiral.global.v1alpha.TrafficGroup")
}

func init() { proto.RegisterFile("globalrouting.proto", fileDescriptor_a5c0dc509add6f4f) }

var fileDescriptor_a5c0dc509add6f4f = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5d, 0xef, 0xd2, 0x30,
	0x14, 0xc6, 0xdd, 0xf8, 0x33, 0xf0, 0x08, 0x86, 0x14, 0x24, 0x8b, 0x57, 0x64, 0xe1, 0x82, 0x0b,
	0x5d, 0x22, 0x7a, 0xe1, 0x5b, 0x0c, 0x9a, 0x20, 0x31, 0x59, 0x32, 0x52, 0xd0, 0xa8, 0x77, 0x65,
	0x94, 0xb1, 0x58, 0xd6, 0xa5, 0x2b, 0x98, 0x7d, 0x44, 0xbf, 0x88, 0x9f, 0xc3, 0xb4, 0x2b, 0x84,
	0x99, 0x11, 0xe3, 0x5d, 0x9f, 0x73, 0xfa, 0xfc, 0x4e, 0xce, 0xd3, 0x0d, 0xfa, 0x31, 0xe3, 0x1b,
	0xc2, 0x04, 0x3f, 0xca, 0x24, 0x8d, 0xfd, 0x4c, 0x70, 0xc9, 0xd1, 0x90, 0x6c, 0x0f, 0x89, 0x20,
	0xcc, 0x2f, 0x9b, 0xfe, 0xe9, 0x19, 0x61, 0xd9, 0x9e, 0x78, 0xbf, 0x6d, 0xe8, 0x2f, 0x74, 0x69,
	0x2d, 0xc8, 0x6e, 0x97, 0x44, 0x4b, 0xce, 0x92, 0xa8, 0x40, 0x2b, 0xe8, 0xca, 0xeb, 0x82, 0x6b,
	0x8d, 0x1a, 0x93, 0x07, 0xd3, 0xa7, 0x7e, 0x3d, 0xc7, 0x0f, 0x78, 0x44, 0x58, 0x22, 0x8b, 0x0a,
	0x05, 0x57, 0x19, 0x08, 0x43, 0x37, 0xa7, 0xf1, 0x81, 0xa6, 0xd2, 0x40, 0x6d, 0x0d, 0x7d, 0x72,
	0x0b, 0xba, 0x2a, 0x2f, 0xe3, 0x72, 0x93, 0x33, 0xb3, 0x82, 0x40, 0x08, 0xee, 0xf6, 0x3c, 0x97,
	0x6e, 0x63, 0x64, 0x4d, 0xee, 0x63, 0x7d, 0x46, 0x9f, 0xa1, 0x9d, 0x53, 0x46, 0x23, 0xc9, 0x85,
	0x7b, 0xa7, 0x47, 0xbc, 0xba, 0x35, 0xa2, 0x66, 0x77, 0x7f, 0x65, 0xbc, 0xf3, 0x54, 0x8a, 0x02,
	0x5f, 0x50, 0x8f, 0xdf, 0x40, 0xb7, 0xd2, 0x42, 0x3d, 0x68, 0xfc, 0xa0, 0x2a, 0x1a, 0x35, 0x5a,
	0x1d, 0xd1, 0x00, 0x9a, 0x27, 0xc2, 0x8e, 0xd4, 0xb5, 0x75, 0xad, 0x14, 0xaf, 0xed, 0x97, 0x96,
	0xf7, 0xcb, 0x82, 0x47, 0xb5, 0x21, 0xa1, 0x00, 0x1c, 0xb6, 0x59, 0x17, 0x59, 0x69, 0x7a, 0x38,
	0x7d, 0xf1, 0x5f, 0x19, 0xfb, 0x81, 0xf6, 0x62, 0xc3, 0x40, 0x6f, 0xc1, 0x91, 0x44, 0xc4, 0x54,
	0x25, 0xa2, 0x36, 0x1f, 0xdf, 0xa2, 0x19, 0xca, 0x42, 0xf0, 0x63, 0x86, 0x8d, 0xc7, 0x1b, 0x83,
	0x53, 0xf2, 0x50, 0x07, 0xda, 0xeb, 0x70, 0x19, 0x06, 0xe1, 0xe2, 0x5b, 0xef, 0x9e, 0x52, 0x1f,
	0xdf, 0x7f, 0x0a, 0xc2, 0x2f, 0x73, 0xdc, 0xb3, 0xbc, 0xaf, 0x30, 0xa8, 0x7b, 0x1a, 0x34, 0x53,
	0xb9, 0xeb, 0x7a, 0x6e, 0xbe, 0x97, 0xf1, 0x3f, 0x9e, 0xb6, 0x9c, 0x7e, 0x71, 0x79, 0x33, 0xe8,
	0x5c, 0x77, 0x90, 0x0b, 0x2d, 0xd3, 0x33, 0x29, 0x9f, 0x25, 0x1a, 0x82, 0xf3, 0x93, 0x26, 0xf1,
	0x5e, 0xea, 0xd4, 0x6c, 0x6c, 0x94, 0xf7, 0x0e, 0x3a, 0xd7, 0x9b, 0xa9, 0x7b, 0x82, 0xc6, 0x09,
	0x4f, 0x0d, 0xc0, 0xa8, 0xbf, 0xfc, 0xcd, 0xb3, 0xff, 0x43, 0xeb, 0x7b, 0xf3, 0xc0, 0xb7, 0x94,
	0x6d, 0x1c, 0xfd, 0xe3, 0x3c, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xed, 0xd7, 0x3b, 0x4f,
	0x03, 0x00, 0x00,
}
